coaches/urls.py
from django.urls import path

from . import views


app_name = "coaches"

urlpatterns = [
    # path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

footballapp/urls.py
from django.contrib import admin
from django.urls import path, include

from personal.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls),

    path("players/", include('players.urls')),
    path("regions/", include('regions.urls')),
    path("matches/", include('matches.urls')),
    path("coaches/", include('coaches.urls')),
]

players/urls.py
from django.urls import path

from . import views


app_name = "players"

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

players/models.py
from django.db import models
from regions.models import Country, City

from model_utils import Choices

from datetime import date
from typing import Any


class Player(models.Model):
    name = models.CharField(max_length=255)
    fullname = models.CharField(max_length=255, blank=True, null=True)
    nationality = models.ForeignKey(Country, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    place_of_birth = models.ForeignKey(City, related_name='players', on_delete=models.CASCADE, blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    primary_position = models.ForeignKey('Position', related_name='primary_position_players', on_delete=models.CASCADE)
    other_position = models.ManyToManyField('Position', related_name='other_position_players', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    PREFERRED_FOOT = Choices(
        (1, 'L', 'Left'),
        (2, 'R', 'Right'),
        (3, 'both', 'Both')
    )
    preferred_foot = models.PositiveSmallIntegerField(choices=PREFERRED_FOOT, blank=True, null=True)

    def __str__(self) -> str:
        return self.name

    @property
    def get_current_teams(self) -> Any:  # getting past circular import
        # print(self.teams.first().start)
        return self.teams.first()

    @property
    def display_age(self) -> str:
        if not self.date_of_birth:
            return 'No Date of Birth'

        today = date.today()
        age = today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        year = today.year - 1 if today.month < self.date_of_birth.month else today.year
        dif = today - date(year, self.date_of_birth.month, self.date_of_birth.day)
        return f'{age} years {dif.days} days'

class Position(models.Model):
    name = models.CharField(max_length=20, unique=True)
    abbreviation = models.CharField(max_length=3, unique=True, db_index=True)
    
    TYPE = Choices(
        (1, 'FW', 'Forward'),
        (2, 'MF', 'Midfielder'),
        (3, 'DF', 'Defender'),
        (4, 'GK', 'Goalkeeper')
    )
    type = models.PositiveSmallIntegerField(choices=TYPE)
    display_order = models.PositiveSmallIntegerField(default=0)

    def __str__(self) -> str:
        return self.abbreviation

class MarketValue(models.Model):
    player = models.ForeignKey('Player', related_name='market_values', on_delete=models.CASCADE)
    value = models.FloatField()
    last_update_value = models.DateField()

players/forms.py
from django import forms

from datetime import date

from .models import Position, Player
from teams.models import PlayerList, Team
from regions.models import City, Country

from typing import List, Any


class PlayerCreationForm(forms.Form):
    name = forms.CharField()
    fullname = forms.CharField(required=False)
    nationality = forms.ModelChoiceField(queryset=None)
    date_of_birth = forms.DateField(required=False)
    place_of_birth = forms.ModelChoiceField(queryset=None, required=False)
    height = forms.IntegerField(required=False)
    primary_position = forms.ModelChoiceField(queryset=None)
    other_position = forms.ModelMultipleChoiceField(queryset=None, widget=forms.CheckboxSelectMultiple(), required=False)
    preferred_foot = forms.TypedChoiceField(choices=Player.PREFERRED_FOOT, coerce=int, initial=Player.PREFERRED_FOOT.R, required=False)

    team = forms.ModelChoiceField(queryset=None)
    start_date = forms.DateField()
    end_date = forms.DateField(required=False)
    shirt_number = forms.IntegerField()
    status = forms.TypedChoiceField(choices=PlayerList.STATUS, coerce=int, initial=PlayerList.STATUS.permanent)

    value = forms.IntegerField(required=False)
    last_updated_value = forms.DateField(required=False)

    def __init__(self, *args: List, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        countries = Country.objects.order_by('name')
        initial_country = Country.objects.get(name="Indonesia")
        self.fields['nationality'].queryset = countries
        self.fields['nationality'].initial = initial_country

        cities = City.objects.order_by('country__id', 'province__name', 'type', 'name')
        self.fields['place_of_birth'].queryset = cities

        positions = Position.objects.order_by('-display_order')
        self.fields['primary_position'].queryset = positions
        self.fields['other_position'].queryset = positions

        teams = Team.objects.order_by('name')
        initial_team = Team.objects.get(id=10)
        self.fields['team'].queryset = teams
        self.fields['team'].initial = initial_team

        self.fields['last_updated_value'].initial = date(2022, 7, 22).strftime('%m/%d/%Y')
    
    def save(self) -> Player:
        name = self.cleaned_data["name"]
        fullname = self.cleaned_data["fullname"]
        nationality = self.cleaned_data["nationality"]
        date_of_birth = self.cleaned_data["date_of_birth"]
        place_of_birth = self.cleaned_data["place_of_birth"]
        height = self.cleaned_data["height"]
        primary_position = self.cleaned_data["primary_position"]
        other_position = self.cleaned_data["other_position"]
        preferred_foot = self.cleaned_data["preferred_foot"]

        team = self.cleaned_data["team"]
        start_date = self.cleaned_data["start_date"]
        end_date = self.cleaned_data["end_date"]
        shirt_number = self.cleaned_data["shirt_number"]
        status = self.cleaned_data["status"]

        value = self.cleaned_data["value"]
        last_updated_value = self.cleaned_data["last_updated_value"]

        player = Player.objects.create(
            name=name, fullname=fullname, nationality=nationality, date_of_birth=date_of_birth,
            place_of_birth=place_of_birth, height=height, primary_position=primary_position,
            preferred_foot=preferred_foot
        )

        player.other_position.set(other_position)

        PlayerList.objects.create(
            team=team, player=player, start=start_date, end=end_date,
            shirt_number=shirt_number, status=status
        )

        if value:
            player.market_values.create(
                value=value, last_update_value=last_updated_value
            )

        return player

players/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.contrib import messages
from django.urls import reverse

from django.core.paginator import Paginator

from .models import Player
from .forms import PlayerCreationForm


def index(request: HttpRequest) -> HttpResponse:
    players = Player.objects.order_by('name')

    page = request.GET.get('page', 1)
    paginator = Paginator(players, per_page=10)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page)

    context_data = {
        "players": page_object
    }
    return render(request, "players/index.html", context_data)

def add(request: HttpRequest) -> HttpResponse:

    form = PlayerCreationForm(data=request.POST or None)
    if form.is_valid():
        player = form.save()
        messages.success(request, f"Player successfully created. {player} ({player.get_current_teams})")
        return redirect(reverse("players:add"))

    context_data = {
        "title": "Add Player",
        "current_page": "players",
        "form": form
    }
    return render(request, "players/add.html", context_data)

players/templates/players/add.html
{% extends 'base.html' %}

{% block content %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible shadow-inset fade show" role="alert">
    <span class="alert-inner--icon"><span class="far fa-thumbs-up"></span></span>
    <span class="alert-inner--text"><strong>Well done!</strong> {{ message }}.</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="container z-2">
    <div class="row">
        <div class="col">
            <h2 class="h5">{{ title }}</h2>
            {{ form.non_field_errors }}
        </div>
    </div>
</div>

<div class="section section-lg pt-4">
    <div class="container">
        <form method="POST">{% csrf_token %}
            <div class="row mb-4 mb-lg-5">
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}">Name</label>
                        {{ form.name }}
                        <!-- <div class="valid-feedback"> # is-valid / is-invalid
                        Looks good!
                        </div>-->
                        <div class="invalid-feedback">
                            {{ form.name.errors }}
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label for="{{ form.fullname.id_for_label }}">Fullname</label>
                        {{ form.fullname }}
                        <div class="invalid-feedback">
                            {{ form.fullname.errors }}
                        </div>               
                    </div>
                    <div class="form-group">
                        <label for="{{ form.nationality.id_for_label }}">Nationality</label>
                        {{ form.nationality }}
                        <div class="invalid-feedback">
                            {{ form.nationality.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.date_of_birth.id_for_label }}">Date of Birth</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.date_of_birth }}
                            <div class="invalid-feedback">
                                {{ form.date_of_birth.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.place_of_birth.id_for_label }}">Place of Birth</label>
                        {{ form.place_of_birth }}
                        <div class="invalid-feedback">
                            {{ form.place_of_birth.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.height.id_for_label }}">Height</label>
                        {{ form.height }}
                        <div class="invalid-feedback">
                            {{ form.height.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.primary_position.id_for_label }}">Primary Position</label>
                        {{ form.primary_position }}
                        <div class="invalid-feedback">
                            {{ form.primary_position.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.other_position.id_for_label }}">Other Position</label>
                        {{ form.other_position }}
                        <div class="invalid-feedback">
                            {{ form.other_position.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.preferred_foot.id_for_label }}">Preferred Foot</label>
                        {{ form.preferred_foot }}
                        <div class="invalid-feedback">
                            {{ form.preferred_foot.errors }}
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label for="{{ form.team.id_for_label }}">Team</label>
                        {{ form.team }}
                        <div class="invalid-feedback">
                            {{ form.team.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.start_date.id_for_label }}">Start Date</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.start_date }}
                            <div class="invalid-feedback">
                                {{ form.start_date.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.end_date.id_for_label }}">End Date</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.end_date }}
                            <div class="invalid-feedback">
                                {{ form.end_date.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.shirt_number.id_for_label }}">Shirt Number</label>
                        {{ form.shirt_number }}
                        <div class="invalid-feedback">
                            {{ form.shirt_number.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.status.id_for_label }}">Status</label>
                        {{ form.status }}
                        <div class="invalid-feedback">
                            {{ form.status.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.value.id_for_label }}">Market Value</label>
                        {{ form.value }}
                        <div class="invalid-feedback">
                            {{ form.value.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_updated_value.id_for_label }}">Last Updated Value</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.last_updated_value }}
                            <div class="invalid-feedback">
                                {{ form.last_updated_value.errors }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $("#id_name").addClass("form-control");
    $("#id_fullname").addClass("form-control");
    $("#id_nationality").addClass("custom-select");
    $("#id_date_of_birth").addClass("form-control datepicker");
    $("#id_place_of_birth").addClass("custom-select");
    $("#id_height").addClass("form-control");
    $("#id_primary_position").addClass("custom-select");
    $("#id_other_position").css("display","flex");
    $("#id_other_position").css("justify-content","space-between");
    $("#id_preferred_foot").addClass("custom-select");

    $("#id_team").addClass("custom-select");
    $("#id_start_date").addClass("form-control datepicker");
    $("#id_end_date").addClass("form-control datepicker");
    $("#id_shirt_number").addClass("form-control");
    $("#id_status").addClass("custom-select");

    $("#id_value").addClass("form-control");
    $("#id_last_updated_value").addClass("form-control datepicker");
</script>
{% endblock %}

players/templates/players/index.html
{% extends 'base.html' %}

{% block content %}
<div class="section bg-primary pt-0 section-lg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="mb-4">
                    <span class="h5">Player List</span>
                </div>
                <div class="table-responsive-sm shadow-soft rounded">
                    <table class="table table-striped">
                        <tr>
                            <th class="border-0" scope="col">Player</th>
                            <th class="border-0" scope="col">Team</th>
                            <th class="border-0" scope="col">Nationality</th>
                            <th class="border-0" scope="col">Age</th>
                            <th class="border-0" scope="col">Place Of Birth (Regency/City)</th>
                            <th class="border-0" scope="col">Place Of Birth (Province)</th>
                            <th class="border-0" scope="col">Height (cm)</th>
                            <th class="border-0" scope="col">Preferred Foot</th>
                        </tr>
                        {% for player in players %}
                        <tr>
                            <td>{{ player.name }}</td>
                            <td>{{ player.get_current_teams }}</td>
                            <td>{{ player.nationality }}</td>
                            <td>{{ player.display_age }}</td>
                            <td>{{ player.place_of_birth|default:"-" }}</td>
                            <td>{{ player.place_of_birth.get_indonesian_province|default:"-" }}</td>
                            <td>{{ player.height|default:"-" }}</td>
                            <td>{{ player.get_preferred_foot_display }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <nav aria-label="Pagination">
            <ul class="pagination" style="justify-content: center;">
                {% for page_number in players.adjusted_elided_pages %}
                    {% if page_number == players.paginator.ELLIPSIS %}
                        {{ page_number }}
                    {% else %}
                        <li  class="page-item{% if page_number == players.number %} active {% endif %}">
                            <a href="{% url 'players:index' %}?page={{ page_number }}" class="page-link">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
</script>
{% endblock %}