coaches/urls.py
from django.urls import path

from . import views


app_name = "coaches"

urlpatterns = [
    # path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

footballapp/urls.py
from django.contrib import admin
from django.urls import path, include

from personal.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls),

    path("players/", include('players.urls')),
    path("regions/", include('regions.urls')),
    path("matches/", include('matches.urls')),
    path("coaches/", include('coaches.urls')),
]

matches/urls.py
from django.urls import path

from . import views


app_name = "matches"

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
    path('<int:id>/add-data/', views.add_data, name="add_data"),
]

matches/models.py
from django.db import models

from competitions.models import Competition
from teams.models import Team
from coaches.models import Coach
from players.models import Player, Position
from regions.models import Country
from stadiums.models import Stadium

from model_utils import Choices


class Match(models.Model):
    competition = models.ForeignKey(Competition, related_name='matches', on_delete=models.CASCADE)
    gameweek = models.PositiveSmallIntegerField(blank=True, null=True)
    home_team = models.ForeignKey(Team, related_name='home_matches', on_delete=models.CASCADE)
    away_team = models.ForeignKey(Team, related_name='away_matches', on_delete=models.CASCADE)
    home_score = models.PositiveSmallIntegerField(default=0)
    away_score = models.PositiveSmallIntegerField(default=0)

    STATUS = Choices(
        (1, 'not_started', 'Not Started'),
        (2, 'half_time', 'Half Time'),
        (3, 'full_time', 'Full Time'),
        (9, 'postponed', 'Postponed')
    )
    status = models.PositiveSmallIntegerField(choices=STATUS, default=STATUS.not_started)

    def __str__(self) -> str:
        match_name = self.home_team.name + " vs " + self.away_team.name
        if self.status == self.STATUS.full_time:
            return match_name + f" ({self.home_score}-{self.away_score})"
        return match_name


class MatchOfficial(models.Model):
    match = models.OneToOneField('Match', related_name='match_officials', on_delete=models.CASCADE)
    referee = models.ForeignKey('Referee', related_name='main_officials', on_delete=models.CASCADE)
    first_assistant_referee = models.ForeignKey('Referee', related_name='first_assistant_officials', on_delete=models.CASCADE, blank=True, null=True)
    second_assistant_referee = models.ForeignKey('Referee', related_name='second_assistant_officials', on_delete=models.CASCADE, blank=True, null=True)
    first_additional_referee = models.ForeignKey('Referee', related_name='first_additional_officials', on_delete=models.CASCADE, blank=True, null=True)
    second_additional_referee = models.ForeignKey('Referee', related_name='second_additional_officials', on_delete=models.CASCADE, blank=True, null=True)
    reserve_referee = models.ForeignKey('Referee', related_name='reserve_officials', on_delete=models.CASCADE, blank=True, null=True)


class MatchData(models.Model):
    match = models.OneToOneField('Match', related_name='match_datas', on_delete=models.CASCADE)
    kick_off_time = models.DateTimeField()  # local time
    stadium = models.ForeignKey(Stadium, related_name='match_datas', on_delete=models.CASCADE)
    attendance = models.IntegerField()
    first_half_added_time = models.PositiveSmallIntegerField()
    second_half_added_time = models.PositiveSmallIntegerField()
    et_first_half_added_time = models.PositiveSmallIntegerField(blank=True, null=True)
    et_second_half_added_time = models.PositiveSmallIntegerField(blank=True, null=True)
    cards = models.ManyToManyField(Player, related_name='match_datas', through='MatchCards', through_fields=('match_data', 'player'))
    lineups = models.ForeignKey('LineUp', related_name='match_datas', on_delete=models.CASCADE)


class Referee(models.Model):
    name = models.CharField(max_length=100)
    nationality = models.ForeignKey(Country, related_name='referees', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Formation(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class LineUp(models.Model):
    coach = models.ForeignKey(Coach, related_name='match_lineups', on_delete=models.CASCADE)
    team = models.ForeignKey(Team, related_name='match_lineups', on_delete=models.CASCADE, blank=True, null=True)
    formation = models.ForeignKey(Formation, related_name='match_lineups', on_delete=models.CASCADE)
    starting = models.ManyToManyField(Player, related_name='match_starting_lineups', through='PlayerRoleProxy', through_fields=('lineup', 'player'))
    reserved = models.ManyToManyField(Player, related_name='match_reserved_lineups', through='PlayerRole', through_fields=('lineup', 'player'))


class Substitution(models.Model):
    match = models.ForeignKey('Match', related_name='substitutions', on_delete=models.CASCADE)
    team = models.ForeignKey(Team, related_name='substitutions', on_delete=models.CASCADE, blank=True, null=True)
    player_out = models.ForeignKey(Player, related_name='out_substitutions', on_delete=models.CASCADE)
    player_in = models.ForeignKey(Player, related_name='in_substitutions', on_delete=models.CASCADE)

    HALF = Choices(
        (1, 'first_half', 'First Half'),
        (2, 'second_half', 'Second Half'),
        (3, 'first_half_et', 'Extra Time First Half'),
        (4, 'second_half_et', 'Extra Time Second Half')
    )
    half = models.PositiveSmallIntegerField(choices=HALF)

    minute = models.PositiveIntegerField()


class Goals(models.Model):
    match = models.ForeignKey('Match', related_name='goals', on_delete=models.CASCADE)
    team = models.ForeignKey(Team, related_name='goals', on_delete=models.CASCADE, blank=True, null=True)
    scorer = models.ForeignKey(Player, related_name='goal_scorers', on_delete=models.CASCADE)
    assist = models.ForeignKey(Player, related_name='goal_assists', on_delete=models.CASCADE, blank=True, null=True)
    second_assist = models.ForeignKey(Player, related_name='goal_second_assists', on_delete=models.CASCADE, blank=True, null=True)

    HALF = Choices(
        (1, 'first_half', 'First Half'),
        (2, 'second_half', 'Second Half'),
        (3, 'first_half_et', 'Extra Time First Half'),
        (4, 'second_half_et', 'Extra Time Second Half'),
        (5, 'penalty_shootout', 'Penalty Shoot-Out')
    )
    half = models.PositiveSmallIntegerField(choices=HALF)

    minute = models.PositiveIntegerField()

    BODY_PART = Choices(
        (1, 'head', 'Head'),
        (2, 'left_foot', 'Left Foot'),
        (3, 'right_foot', 'Right Foot'),
        (9, 'other', 'Other')
    )
    goal_body_part = models.PositiveSmallIntegerField(choices=BODY_PART)
    assist_body_part = models.PositiveSmallIntegerField(choices=BODY_PART, blank=True, null=True)

    CATEGORY = Choices(
        (1, 'progressive_pass', 'Progressive Pass'),
        (2, 'basic_pass', 'Basic Pass'),
        (3, 'set_piece_pass', 'Set Piece Pass'),
        (4, 'set_piece_kick', 'Set Piece Kick'),
        (5, 'individual_play', 'Individual Play'),
        (9, 'own_goal', 'Own Goal'),
    )
    category = models.PositiveSmallIntegerField(choices=CATEGORY)

    AREA_OF_SHOOT = Choices(
        (1, '6_yard_box', '6 Yard Box'),
        (2, 'penalty_box', 'Penalty Box'),
        (3, 'outside_penalty_box', 'Outside Penalty Box')
    )
    area_of_shoot = models.PositiveSmallIntegerField(choices=AREA_OF_SHOOT)

    SET_PIECES_TYPE = Choices(
        (1, 'free_kick', 'Free Kick'),
        (2, 'corner_kick', 'Corner Kick'),
        (3, 'penalty_kick', 'Penalty Kick'),
        (4, 'throw_in', 'Throw In')
    )
    set_pieces_type = models.PositiveSmallIntegerField(choices=SET_PIECES_TYPE, blank=True, null=True)

    ATTACKING_FLANKS = Choices(
        (1, 'left', 'Left'),
        (2, 'right', 'Right')
    )
    attacking_flanks = models.PositiveSmallIntegerField(choices=ATTACKING_FLANKS, blank=True, null=True)

    is_deflected = models.BooleanField(default=False)
    error_leading_to_goal = models.BooleanField(default=False)

    ASSIST_PASS_TYPE = Choices(
        (1, 'cross', 'Cross'),
        (2, 'deep_completed_cross', 'Deep Completed Cross'),
        (3, 'deflected_cross', 'Deflected Cross'),
        (4, 'deep_completion', 'Deep Completion'),
        (5, 'head_pass', 'Head Pass'),
        (6, 'progressive_pass', 'Progressive Pass'),
        (90, 'rebound', 'Rebound')
    )
    assist_pass_type = models.PositiveSmallIntegerField(choices=ASSIST_PASS_TYPE, blank=True, null=True)


class MissedPenalty(models.Model):
    match = models.ForeignKey('Match', related_name='missed_penalties', on_delete=models.CASCADE)
    team = models.ForeignKey(Team, related_name='missed_penalties', on_delete=models.CASCADE, blank=True, null=True)
    penalty_taker = models.ForeignKey(Player, related_name='missed_penalties', on_delete=models.CASCADE)

    TYPE = Choices(
        (1, 'saved', 'Saved'),
        (2, 'missed', 'Missed'),
        (3, 'hit_the_crossbar', 'Hit the Crossbar'),
    )
    type = models.PositiveSmallIntegerField(choices=TYPE)

    HALF = Choices(
        (1, 'first_half', 'First Half'),
        (2, 'second_half', 'Second Half'),
        (3, 'first_half_et', 'Extra Time First Half'),
        (4, 'second_half_et', 'Extra Time Second Half'),
        (5, 'penaltiy_shootout', 'Penalty Shoot-Out')
    )
    half = models.PositiveSmallIntegerField(choices=HALF)

    minute = models.PositiveIntegerField()


class MatchCards(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    match_data = models.ForeignKey('MatchData', on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, blank=True, null=True)

    HALF = Choices(
        (1, 'first_half', 'First Half'),
        (2, 'second_half', 'Second Half'),
        (3, 'first_half_et', 'Extra Time First Half'),
        (4, 'second_half_et', 'Extra Time Second Half')
    )
    half = models.PositiveSmallIntegerField(choices=HALF)

    TYPE = Choices(
        (1, 'yellow', 'Yellow'),
        (2, 'second_yellow', 'Yellow'),
        (3, 'red', 'Red'),
    )
    type = models.PositiveSmallIntegerField(choices=TYPE)

    minute = models.PositiveIntegerField()

    
class PlayerRole(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    lineup = models.ForeignKey('Lineup', on_delete=models.CASCADE, blank=True, null=True)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    is_captain = models.BooleanField(default=False)


class PlayerRoleProxy(PlayerRole):
    class Meta:

matches/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from django.contrib import messages
from django.urls import reverse

from django.core.paginator import Paginator

from .models import Match
from competitions.models import Competition

from .forms import MatchCreationForm, MatchDataCreationForm


def index(request: HttpRequest) -> HttpResponse:
    competition = Competition.objects.first()
    matches = Match.objects.filter(competition=competition) \
        .order_by('gameweek', 'match_datas__kick_off_time')

    page = request.GET.get('page', 1)
    paginator = Paginator(matches, per_page=10)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page)

    context_data = {
        "competition": competition,
        "matches": page_object
    }
    return render(request, "matches/index.html", context_data)

def add(request: HttpRequest) -> HttpResponse:

    form = MatchCreationForm(data=request.POST or None)
    if form.is_valid():
        match = form.save()
        messages.success(request, f"Macth successfully created. {match.home_team} vs {match.away_team}")
        return redirect(reverse("matches:add"))

    context_data = {
        "title": "Add Match",
        "current_page": "matches",
        "form": form
    }
    return render(request, "matches/add.html", context_data)

def add_data(request: HttpRequest, id: int) -> HttpResponse:
    match = get_object_or_404(Match.objects.select_related('home_team', 'away_team', 'home_team__stadium'),
                              id=id)

    form = MatchDataCreationForm(data=request.POST or None, match=match)
    if form.is_valid():
        match_data = form.save()
        messages.success(request, f"Macth data successfully created. {match_data.match.home_team} vs {match_data.match.away_team}")
        return redirect(reverse("matches:index"))

    context_data = {
        "title": f"Add Match Data {match.home_team} vs {match.away_team}",
        "current_page": "matches",
        "form": form
    }
    return render(request, "matches/add_data.html", context_data)

matches/templates/matches/add.html
{% extends 'base.html' %}

{% block content %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible shadow-inset fade show" role="alert">
    <span class="alert-inner--icon"><span class="far fa-thumbs-up"></span></span>
    <span class="alert-inner--text"><strong>Well done!</strong> {{ message }}.</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="container z-2">
    <div class="row">
        <div class="col">
            <h2 class="h5">{{ title }}</h2>
            {{ form.non_field_errors }}
        </div>
    </div>
</div>

<div class="section section-lg pt-4">
    <div class="container">
        <form method="POST">{% csrf_token %}
            <div class="row mb-4 mb-lg-5">
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label for="{{ form.competition.id_for_label }}">Competition</label>
                        {{ form.competition }}
                        <div class="invalid-feedback">
                            {{ form.competition.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.home_team.id_for_label }}">Home Team</label>
                        {{ form.home_team }}
                        <div class="invalid-feedback">
                            {{ form.home_team.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.home_score.id_for_label }}">Home Score</label>
                        {{ form.home_score }}
                        <div class="invalid-feedback">
                            {{ form.home_score.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.status.id_for_label }}">Status</label>
                        {{ form.status }}
                        <div class="invalid-feedback">
                            {{ form.status.errors }}
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label for="{{ form.gameweek.id_for_label }}">Gameweek</label>
                        {{ form.gameweek }}
                        <div class="invalid-feedback">
                            {{ form.gameweek.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.away_team.id_for_label }}">Away Team</label>
                        {{ form.away_team }}
                        <div class="invalid-feedback">
                            {{ form.away_team.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.away_score.id_for_label }}">Away Score</label>
                        {{ form.away_score }}
                        <div class="invalid-feedback">
                            {{ form.away_score.errors }}
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $("#id_competition").addClass("custom-select");
    $("#id_gameweek").addClass("form-control");
    $("#id_home_team").addClass("custom-select");
    $("#id_away_team").addClass("custom-select");
    $("#id_home_score").addClass("form-control");
    $("#id_away_score").addClass("form-control");
    $("#id_status").addClass("custom-select");

</script>
{% endblock %}

matches/templates/matches/index.html
{% extends 'base.html' %}

{% block content %}
<div class="section bg-primary pt-0 section-lg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="mb-4">
                    <span class="h5">Matches of {{ competition }}</span>
                </div>
                <div class="table-responsive-sm shadow-soft rounded">
                    <table class="table table-striped">
                        <tr>
                            <th class="border-0" scope="col">Gameweek</th>
                            <th class="border-0" scope="col">Date</th>
                            <th class="border-0" scope="col" colspan=3>Match</th>
                            <th class="border-0" scope="col">Status</th>
                            <th class="border-0" scope="col">Match Data</th>
                        </tr>
                        {% for match in matches %}
                        <tr>
                            <td>{{ match.gameweek }}</td>
                            <td></td>
                            <td>{{ match.home_team }}</td>
                            {% if match.status == match.STATUS.full_time %}
                                <td>{{ match.home_score }} - {{ match.away_score }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            <td>{{ match.away_team }}</td>
                            <td>{{ match.get_status_display }}</td>
                            {% if match.match_datas %}
                                <td>View Data</td>
                            {% else %}
                                <td><a href="{% url 'matches:add_data' match.id %}">Add Data</a></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <nav aria-label="Pagination">
            <ul class="pagination" style="justify-content: center;">
                {% for page_number in matches.adjusted_elided_pages %}
                    {% if page_number == matches.paginator.ELLIPSIS %}
                        {{ page_number }}
                    {% else %}
                        <li  class="page-item{% if page_number == matches.number %} active {% endif %}">
                            <a href="{% url 'matches:index' %}?page={{ page_number }}" class="page-link">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
</script>
{% endblock %}