coaches/urls.py
from django.urls import path

from . import views


app_name = "coaches"

urlpatterns = [
    # path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

footballapp/urls.py
from django.contrib import admin
from django.urls import path, include

from personal.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls),

    path("players/", include('players.urls')),
    path("regions/", include('regions.urls')),
    path("matches/", include('matches.urls')),
    path("coaches/", include('coaches.urls')),
]

coaches/models.py
from django.db import models
from regions.models import Country

from typing import Any


class Coach(models.Model):
    name = models.CharField(max_length=255)
    nationality = models.ForeignKey(Country, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return self.name

    @property
    def get_current_teams(self) -> Any:  # getting past circular import
        return self.teams.first()

coaches/forms.py
from django import forms

from .models import Coach
from teams.models import Team, CoachList
from regions.models import Country

from typing import List, Any


class CoachCreationForm(forms.Form):
    name = forms.CharField()
    nationality = forms.ModelChoiceField(queryset=None)
    date_of_birth = forms.DateField(required=False)
    height = forms.IntegerField(required=False)

    team = forms.ModelChoiceField(queryset=None)
    start_date = forms.DateField()
    end_date = forms.DateField(required=False)
    status = forms.TypedChoiceField(choices=CoachList.STATUS, coerce=int, initial=CoachList.STATUS.manager)
    departure_reason = forms.TypedChoiceField(choices=[("", "----")] + CoachList.DEPARTURE_REASON, coerce=int, required=False)

    def __init__(self, *args: List, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        countries = Country.objects.order_by('name')
        self.fields['nationality'].queryset = countries

        teams = Team.objects.order_by('name')
        self.fields['team'].queryset = teams

    def save(self) -> Coach:
        name = self.cleaned_data["name"]
        nationality = self.cleaned_data["nationality"]
        date_of_birth = self.cleaned_data["date_of_birth"]
        height = self.cleaned_data["height"]

        team = self.cleaned_data["team"]
        start_date = self.cleaned_data["start_date"]
        end_date = self.cleaned_data["end_date"]
        status = self.cleaned_data["status"]
        departure_reason = self.cleaned_data["departure_reason"]

        coach = Coach.objects.create(
            name=name, nationality=nationality, date_of_birth=date_of_birth, height=height
        )

        CoachList.objects.create(
            team=team, coach=coach, start=start_date, end=end_date, status=status,
            departure_reason=departure_reason if departure_reason else None
        )

        return coach

coaches/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse

from .forms import CoachCreationForm


def add(request: HttpRequest) -> HttpResponse:

    form = CoachCreationForm(data=request.POST or None)
    if form.is_valid():
        coach = form.save()
        messages.success(request, f"Coach successfully created. {coach} ({coach.get_current_teams})")
        return redirect(reverse("coaches:add"))

    context_data = {
        "title": "Add Coach",
        "current_page": "coaches",
        "form": form
    }
    return render(request, "coaches/add.html", context_data)

coaches/templates/coaches/add.html
{% extends 'base.html' %}

{% block content %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible shadow-inset fade show" role="alert">
    <span class="alert-inner--icon"><span class="far fa-thumbs-up"></span></span>
    <span class="alert-inner--text"><strong>Well done!</strong> {{ message }}.</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="container z-2">
    <div class="row">
        <div class="col">
            <h2 class="h5">{{ title }}</h2>
            {{ form.non_field_errors }}
        </div>
    </div>
</div>

<div class="section section-lg pt-4">
    <div class="container">
        <form method="POST">{% csrf_token %}
            <div class="row mb-4 mb-lg-5">
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}">Name</label>
                        {{ form.name }}
                        <div class="invalid-feedback">
                            {{ form.name.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.nationality.id_for_label }}">Nationality</label>
                        {{ form.nationality }}
                        <div class="invalid-feedback">
                            {{ form.nationality.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.date_of_birth.id_for_label }}">Date of Birth</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.date_of_birth }}
                            <div class="invalid-feedback">
                                {{ form.date_of_birth.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.height.id_for_label }}">Height</label>
                        {{ form.height }}
                        <div class="invalid-feedback">
                            {{ form.height.errors }}
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label for="{{ form.team.id_for_label }}">Team</label>
                        {{ form.team }}
                        <div class="invalid-feedback">
                            {{ form.team.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.start_date.id_for_label }}">Start Date</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.start_date }}
                            <div class="invalid-feedback">
                                {{ form.start_date.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.end_date.id_for_label }}">End Date</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                            </div>
                            {{ form.end_date }}
                            <div class="invalid-feedback">
                                {{ form.end_date.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.status.id_for_label }}">Status</label>
                        {{ form.status }}
                        <div class="invalid-feedback">
                            {{ form.status.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.departure_reason.id_for_label }}">Departure Reason</label>
                        {{ form.departure_reason }}
                        <div class="invalid-feedback">
                            {{ form.departure_reason.errors }}
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $("#id_name").addClass("form-control");
    $("#id_nationality").addClass("custom-select");
    $("#id_date_of_birth").addClass("form-control datepicker");
    $("#id_height").addClass("form-control");

    $("#id_team").addClass("custom-select");
    $("#id_start_date").addClass("form-control datepicker");
    $("#id_end_date").addClass("form-control datepicker");
    $("#id_status").addClass("custom-select");
    $("#id_departure_reason").addClass("custom-select");
</script>
{% endblock %}